Implement new logging API
couchbase/couchbase-lite-java-common pull request #361
Opened 2024-12-31 18:42 UTC by bmeike

There are two deviations from the v4 spec here:
- the class FileLogSink is not final.
- the class ConsoleLogSink is not final.

Making it these two classes final would require really, really complex code.  There is already precedent for visible functions that are not supported parts of the public API.  These two methods are appropriately commented and can be made final as soon as the legacy logging system is removed

Several of the changes are necessary just to make old Log tests work with the (unnecessary in this implementation) change that makes it illegal to use the new and old logging systems in the same application.

2025-01-06 19:05 UTC, pasin requested changes

2025-01-06 19:05 UTC, pasin commented on common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java
> +        // ignore the file logger's domains
This would mean that newDomains will always contain all domains because file logging is for all domains?

2025-01-06 19:05 UTC, pasin commented on common/main/java/com/couchbase/lite/logging/FileLogSink.java
> +        private int maxKeptFiles = Defaults.LogFile.MAX_ROTATE_COUNT;
maxKeptFiles = Defaults.LogFile.MAX_ROTATE_COUNT + 1.

2025-01-06 20:08 UTC, bmeike commented on android/main/java/com/couchbase/lite/logging/ConsoleLogSink.java
> +    public ConsoleLogSink(@NonNull LogLevel level, @NonNull Set<LogDomain> domains) {
Fixed in the spec and in the code....

2025-01-06 20:39 UTC, bmeike commented on common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java
> +        // ignore the file logger's domains
fixed

2025-01-06 20:41 UTC, bmeike commented on common/main/java/com/couchbase/lite/FileLogger.java
> +                fileLogger.getMaxKeptFiles(),
fixed

2025-01-06 21:10 UTC, bmeike commented on common/main/java/com/couchbase/lite/FileLogger.java
> +                    .setMaxKeptFiles(config.getMaxRotateCount())
fixed

2025-01-07 22:33 UTC, bmeike commented on common/main/java/com/couchbase/lite/internal/logging/LogSinksImpl.java
> +        // ignore the file logger's domains
You are absolutely right.  I completely misunderstood the issue.  Fixed.

2025-01-07 23:01 UTC, bmeike commented
I've added the following fixes since I originally put this PR up:
- Make sure Java doesn’t confuse ConsoleLogSink(LogLevel level) with ConsoleLogSink(LogLevel level, LogDomain... domains)
- Convert maxKeptFiles to maxRotateCount in call to LiteCore
- remove a pointless test and the hair it depended on.
- Use autogenerated FileSink defaults
- fix testFileLoggingMaxSize  and add testFileLoggingMaxKeptFiles

2025-01-07 23:06 UTC, borrrden approved these changes

2025-01-07 23:10 UTC, merged