Modify delays on tests, fix some of the tests that are not testing what they claim to
couchbase/couchbase-lite-java-common pull request #48
Opened 2021-11-09 01:27 UTC by LaurenNguyen14

2021-11-10 01:13 UTC, bmeike requested changes
So... Being all hard-ass about this one:
- Watch your formatting.  Please nake your code look as much like existing code as you possible can.  Check your spelling.  Run InspectCode... on files you change.
- LiveQuery implementation just changed completely.  You are responsible for making sure that we have a complete and useful set of tests.  Please step through each one of these tests to verify that it tests something that needs to be tested, that it actually tests the thing it says it tests, and that the test itself is simple, bug free and easy for the next person to understand.
- Those little yellow flags, on the right of your Android Studio window?  Please pay attention to them.  In tests, I don't care if there is the possibility of an NPE (and, in fact you can use @SuppressWarnings("ConstantConditions") to make those warnings go away. Don't do that in production, though).  Most other stuff, though is there to tell you your code has problems.  Fix them.

2021-11-10 01:13 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
>      }
I don't believe this test is testing anything.  Would you either say what it is testing or remove it

Here's the original test.  I don't know how it got turned into what it is now.
https://github.com/couchbase/couchbase-lite-android/blob/4cb39c1c7f69dd6d8e50d75997de7618327215db/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LiveQueryTest.java#L62-L141

I gotta tell you, I just spent nearly 15 minutes assuring myself that it wasn't me that made this test useless ;-P

If you can make sense of the original, cool.  If not, I guess we can just dump it.  It hasn't been testing anything at all for at least 2 years.


S

2021-11-10 01:13 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
>      public void testLiveQueryRefresh() throws CouchbaseLiteException, InterruptedException {
Great looking test.  I love how it explains what it is doing.

2021-11-10 17:32 UTC, LaurenNguyen14 commented on common/main/java/com/couchbase/lite/AbstractQuery.java
> +            10, // 10 ms delay. work around for CBL-2543. There won't be any delay after CBL-2543 is fixed
There's not a note in 2543, but i can add one

2021-11-11 21:52 UTC, bmeike requested changes
Looking much better.  Still some things to fix.

Please check all of your lambdas to make sure they are thread safe.  I think they are not.  Specifically:

int[] foo = {0};
runThisOnSomeThread(n -> foo[0] = n)
while (foo[0] <= 0) {   ... }

Is absolutely not thread safe.

2021-11-11 21:52 UTC, bmeike commented on common/main/java/com/couchbase/lite/AbstractQuery.java
> +            10, // !!! 10 ms delay. work around for CBL-2543. There won't be any delay after CBL-2543 is fixed
Excellent.  We need a way to guarantee that this gets removed, when the bug is closed.

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +    private static final long TOLERABLE_DATABASE_CHANGE_DELAY = 600;
I think this should be written:
private static final long QUERY_DEBOUNCE_DELAY_MS = 500;

 "QUERY_DEBOUNCE_DELAY + QUERY_RUN_TIME + ((QUERY_DEBOUNCE_DELAY + QUERY_RUN_TIME) * 0.1)" or something.  Please show your work.  When something changes it needs to be easy for the next guy to figure out what to change.  If you add up all the numbers it is impossible to figure out what comes from the spec and what is your slop factor.
 
 Also, all time constants must include their units, in their names: _SEC, _MS, _MIN, etc

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                int n = count[0]++;
I still wish you'd get rid of that variable...  this could be an expression lambda...

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +        assertTrue(latch1[0].await(TOLERABLE_QUERY_RUN_TIME, TimeUnit.MILLISECONDS));
If this assert fails the test will terminate without removing the first change listener.

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                    if (rs != null) {
This is really weird.  The try-with-resources is going to close the rs, but it is closed again, in the `if`.  What is this supposed to be doing?

I probably failed to notice that, last time I looked at this....  Sorry.

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
>      @Test
The name is pretty descriptive.  That's great.  I still think a little comment that described what the test is doing, would be excellent.

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                        if (r != null && Objects.equals(r.getString(0), "doc-11")) {
Single line?

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                if (rs != null && rs.allResults().size() == count[0] + 1) {
Please put in parenthesis.

2021-11-11 21:52 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +    @SuppressWarnings("ConstantConditions")
You should probably apply this to the whole class.  As I say, never, never in production... In the tests, it is fine.

2021-11-12 22:22 UTC, bmeike requested changes
Looking really good.  There's one place that I'd like you to use an idiom and a few places that the thread-safety still isn't quite right.

Almost there!

2021-11-12 22:22 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                //this try-with resources will close the rs
Yeah... right... but the whole point of this test is closing the resultSet.  What would you think of:
change -> {
    change.getResults().close()
    latches[atmCount.getAndIncrement(0)].countDown();
}

2021-11-12 22:22 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                        latch[atmCount.get(0)].countDown();
you'll need to use getAndIncrement here, too

2021-11-15 20:39 UTC, bmeike approved these changes
Fix that one try/finally and you are good to go.

2021-11-15 20:39 UTC, bmeike commented on common/test/java/com/couchbase/lite/LiveQueryTest.java
> +                token2 = query.addChangeListener(
So... I think the idiom is:
do something
try { ... }
finally { undo it }

You have two quite different things, here.  First is the idiom as described above, but this time you have:
try { 
do something
...
}
finally { undo it }

One or the other....

2021-11-15 21:14 UTC, merged