CBL-3023: correctly handle SocketTimeoutException
couchbase/couchbase-lite-java-common pull request #70
Opened 2022-04-20 18:08 UTC by bmeike

Correct handling of SocketTimeoutException.  Similar treatment of PortUnreachableException and NoRouteToHostException

@borrrden : will the use of domain `C4Constants.ErrorDomain.NETWORK` and code `C4Constants.NetworkError.HOST_UNREACHABLE` work in Hydrogen LiteCore?

2022-04-20 22:44 UTC, borrrden commented
No unfortunately, those constants are not present in Hydrogen.

2022-04-20 22:46 UTC, borrrden requested changes
This won't work as is (thanks for the heads up).  Either Core or Java needs to change.  As it stands I am not sure what will happen if this is merged.  Probably turn into an "unknown error" of sorts.

2022-04-20 22:49 UTC, borrrden commented
Note:  We do have `kC4NetErrTimeout` (3) in the network domain in hydrogen, which is retryable.

2022-04-22 00:01 UTC, LaurenNguyen14 approved these changes

2022-04-22 00:40 UTC, borrrden approved these changes

2022-04-22 16:38 UTC, merged